### ISSUE TITLE
Reset password expiresIn error

### ISSUE THREAD

**Issue by gochuicod** [PSITS-UC-MAIN/PSITS-WEB#40]
![image](https://github.com/PSITS-UC-MAIN/PSITS-WEB/assets/71744890/203a84cb-135e-4ec8-b580-f9458d1fe261)

Need nig fix gaw, not urgent but needed.

**Comment by jaymar921** [comment]
Nice na spot dayun, take your time @Keeeyaan

**Comment by Keeeyaan** [comment]
Fixed!
